### ISSUE TITLE
Support for guzzlehttp/guzzle v7+ needed

### ISSUE THREAD

**Issue by sarunazs** [paysera/lib-rest-client-common#10]
paysera/lib-rest-client-common[1.0.0, ..., 1.1.1, 2.1.0, ..., 2.5.0] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).

**Comment by borilyordanov** [comment]
I'm closing this issue, support was added with #11.
